### ISSUE TITLE
Error when env variable 'repo' = this 

### ISSUE THREAD

**Issue by alexsanro** [alice-biometrics/release-creator#6]
Exist an error when the env variable `repo = this`. But work correctly if you specific the name of the repo for example 'alexsanro/xxxx'. 

```
with:
    GITHUB_TOKEN: ***
    version: vx.x.x
    description: "Description"
    repo: this
    branch: master
    draft: false
    prerelease: false
  env:
    VERSION: x.x.x
```

    
    `/src/releaser.sh: line 12: repo: readonly variable`

**Comment by acostapazo** [comment]
@alexsanro thanks for reporting this bug.

Version `1.0.5` should solve your issue :) 

```yml
update:
    runs-on: ubuntu-latest
    name: Create a release
    steps:
      - uses: alice-biometrics/release-creator/@v1.0.5
        with:
            GITHUB_TOKEN: ***
            version: vx.x.x
            description: "Description"
            repo: this
            branch: master
            draft: false
            prerelease: false
          env:
            VERSION: x.x.x
```
